services:
  megabead-mongo:
    image: mongo:7
    container_name: megabead-mongo
    restart: unless-stopped
    volumes:
      - megabead_mongo_data:/data/db
    networks:
      - megabead

  backend:
    build: ./backend
    container_name: megabead-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=8181
    depends_on:
      - megabead-mongo
    volumes:
      - ./backend/products/product-images:/app/products/product-images
    networks:
      - megabead

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: megabead-frontend
    restart: unless-stopped
    networks:
      - megabead
      - adam-cloud

volumes:
  megabead_mongo_data:

networks:
  megabead:
    driver: bridge
  adam-cloud:
    external: true
